In [1]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv("/content/sample_data/numbers.csv")
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel780  pixel781  pixel782  pixel783  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 785 columns]

In [30]:
data=np.array(data)
print(data)
np.random.shuffle(data)

[[6. 0. 0. ... 0. 0. 0.]
 [6. 0. 0. ... 0. 0. 0.]
 [9. 0. 0. ... 0. 0. 0.]
 ...
 [9. 0. 0. ... 0. 0. 0.]
 [8. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [35]:
m=data.shape[0]

In [36]:
train=data[:int(m*0.8), :] #80% train data
test=data[int(m*0.8):m,:] #20% test data

In [39]:
x_train=train[:,1:].T
y_train=train[:,0]
x_test=test[:,1:].T
y_test=test[:,0]

x_train=x_train/255
x_test=x_test/255



In [40]:

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(784, 22028)
(22028,)
(784, 5508)
(5508,)


In [41]:
print(x_train[:5])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [42]:
def intialize(x):

    n=x.shape[0]
    w1=np.random.rand(10,n)-0.5
    b1=np.random.rand(10,1)-0.5
    w2=np.random.rand(10,10)-0.5
    b2=np.random.rand(10,1)-0.5
    return w1,b1,w2,b2

def Relu(x):
    return np.maximum(x,0)

def softmax(x):
    total=sum(np.exp(x))
    return np.exp(x)/total

def forward(x,w1,b1,w2,b2):
    a0=x
    z1=w1.dot(a0)+b1
    a1=Relu(z1)
    z2=w2.dot(a1)+b2
    a2=softmax(z2)
    return z1,a1,z2,a2

def num_encode(Y):
  Y=Y.astype(int)
  one_hot_Y = np.zeros((Y.size, Y.max() + 1))
  one_hot_Y[np.arange(Y.size), Y] = 1
  return one_hot_Y.T


def backward(w1,b1,w2,b2,z1,a1,z2,a2,x,y):
    m=x.shape[1]
    y=num_encode(y)

    dz2=a2-y
    dw2=1/m*(dz2.dot(a1.T))
    db2=1/m*(np.sum(dz2))

    dz1=w2.T.dot(dz2)*(z1>0)
    dw1=1/m*(dz1.dot(x.T))
    db1=1/m*(np.sum(dz1))

    return dw1,db1,dw2,db2



def updata_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha):
    w1=w1-alpha*dw1
    b1=b1-alpha*db1
    w2=w2-alpha*dw2
    b2=b2-alpha*db2

    return w1,b1,w2,b2


def predict(a2):
    return np.argmax(a2,0)


def accuracy(y_cap,y):
    return np.sum(y_cap==y)/y.size


def train(x,y,alpha,epochs):
    w1,b1,w2,b2=intialize(x)

    for i in range(epochs):
        z1,a1,z2,a2=forward(x,w1,b1,w2,b2)
        dw1,db1,dw2,db2=backward(w1,b1,w2,b2,z1,a1,z2,a2,x,y)
        w1,b1,w2,b2=updata_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha)

        if (i%20)==0:
            print("Iteration number: ", i)
            print("Accuracy = ", accuracy(predict(a2), y))

    return w1,b1,w2,b2


In [44]:
w1,b1,w2,b2=train(x_train,y_train,0.1,500)

Iteration number:  0
Accuracy =  0.08834211004176502
Iteration number:  20
Accuracy =  0.19997276193934993
Iteration number:  40
Accuracy =  0.37234428908661704
Iteration number:  60
Accuracy =  0.4340384964590521
Iteration number:  80
Accuracy =  0.49282731069547847
Iteration number:  100
Accuracy =  0.5384964590521155
Iteration number:  120
Accuracy =  0.5739513346649718
Iteration number:  140
Accuracy =  0.603686217541311
Iteration number:  160
Accuracy =  0.628336662429635
Iteration number:  180
Accuracy =  0.6510350463047031
Iteration number:  200
Accuracy =  0.6715997820955149
Iteration number:  220
Accuracy =  0.6892591247503178
Iteration number:  240
Accuracy =  0.7048756128563646
Iteration number:  260
Accuracy =  0.7209460686399128
Iteration number:  280
Accuracy =  0.7339295442164517
Iteration number:  300
Accuracy =  0.7474123842382422
Iteration number:  320
Accuracy =  0.7591701470855275
Iteration number:  340
Accuracy =  0.768658071545306
Iteration number:  360
Accuracy =